export const STORTINGET_ACTIVE_SESSION_ID =
  process.env.STORTINGET_SESSION_ID || process.env.NEXT_PUBLIC_STORTINGET_SESSION_ID || '2025-2026';

export const STORTINGET_ACTIVE_PERIODE_ID =
  process.env.STORTINGET_PERIODE_ID || process.env.NEXT_PUBLIC_STORTINGET_PERIODE_ID || '2025-2029';

